#!/usr/bin/env python3
"""Generate portable skill resources and ChatGPT instructions from the shared rules.

Run from any directory. --check verifies checked-in exports without modifying files.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import inject
import pace
import pace_config

ROOT = Path(__file__).resolve().parent.parent


def exports() -> dict:
    cfg = pace_config.defaults()
    instructions = (
        "Use human-pace for replies in this conversation until I change or disable it.\n"
        + inject.build_rules(cfg) + "\n"
        "If I ask for human-pace off, stop applying these formatting preferences.\n"
    )
    sections = ["# Formatting settings\n",
                "Generated by scripts/export_openai.py; edit rules/*.md instead.\n",
                "## Common scope\n\n" + inject.read_fragment(inject.RULES_DIR, "common.md") + "\n"]
    for preset in ("focus", "light", "off"):
        rules = inject.build_rules({**cfg, **pace.PRESETS[preset]})
        sections.append(f"## Preset {preset}\n\n{rules or inject.OFF_NOTICE}\n")
    for key, filename in inject.FRAGMENTS:
        if filename:
            sections.append(f"## {key}\n\n{inject.read_fragment(inject.RULES_DIR, filename)}\n")
    for approach, filename in inject.BIONIC_FRAGMENTS.items():
        sections.append(f"## Bionic {approach}\n\n{inject.read_fragment(inject.RULES_DIR, filename)}\n")
    return {
        ROOT / "integrations/chatgpt/custom-instructions.txt": instructions,
        ROOT / "skills/human-pace/references/settings.md": "\n".join(sections),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated resources are stale")
    args = parser.parse_args(argv)
    stale = []
    for path, content in exports().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Stale exports: " + ", ".join(stale))
        print("Run python3 scripts/export_openai.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
